version: '3.8'
services:
  node:
    image: node:alpine
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: 'production'
      #TOKEN_SECRET_WORD: ' '
      #TOKEN_EXPIRATION_TIME: ' '
      #PORT: 
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: "npm run start"
  mongo: 
    image: mongo:7.0.5-rc0-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'usuario'
      MONGO_INITDB_ROOT_PASSWORD: 'passusuario'
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'usuario'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'passusuario'
      ME_CONFIG_MONGODB_URL: mongodb://usuario:passusuario@mongo:27017/
      ME_CONFIG_MONGODB_AUTH_USERNAME: 'usuario'
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 'passusuario'

volumes:
  mongodata:
    driver: local